FROM node:16-slim

RUN apt-get update
RUN apt-get -y install git python3 build-essential

# Default workdir
# WORKDIR /srv

# COPY ./src .

# RUN yarn

# CMD ["yarn", "start"]

# WORKDIR /srv/source

# EXPOSE 3001